"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v2)yl!b9zbu8jiw6@g3qqoor28*&$7qt)_qf3@gn5%*o6ta2*-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mptt',
    'django.contrib.admin',
    'import_export',
    "ckeditor",
    "ckeditor_uploader",
    'accounts',
    'rulebook',
    'items',
    'magic',
    'character',
    'worlds',
    'maps',
    'shops',
]
AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [
    BASE_DIR / "static_files",
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

CKEDITOR_UPLOAD_PATH = "uploads/"

# Конфигуратор редактора
CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "Full",  # можно настроить свой тулбар
        "height": 400,
        "width": "100%",
        # подключаем плагин markdown (см. шаг 3)
        "extraPlugins": "markdown",
        # при желании можно отключить очистку тегов
        "removePlugins": "stylesheetparser",
        # чтобы ссылка на превью картинок работала
        "filebrowserUploadUrl": "/ckeditor/upload/",
        "filebrowserBrowseUrl": "/ckeditor/browse/",
    },
}

UNFOLD = {
    "SITE_TITLE": "RPTG Admin",
    "SITE_HEADER": "RPTG",
    "SITE_SUBHEADER": _("Панель управления ролевой площадкой"),
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Обзор"),
                "items": [
                    {
                        "title": _("Дэшборд"),
                        "icon": "space_dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Пользователи и доступ"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Пользователи"),
                        "icon": "group",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                    {
                        "title": _("Группы"),
                        "icon": "admin_panel_settings",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("Миры и карты"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Миры"),
                        "icon": "public",
                        "link": reverse_lazy("admin:worlds_world_changelist"),
                    },
                    {
                        "title": _("Приглашения"),
                        "icon": "mail",
                        "link": reverse_lazy("admin:worlds_worldinvitation_changelist"),
                    },
                    {
                        "title": _("Локации"),
                        "icon": "explore",
                        "link": reverse_lazy("admin:maps_location_changelist"),
                    },
                    {
                        "title": _("Токены карт"),
                        "icon": "location_on",
                        "link": reverse_lazy("admin:maps_maptoken_changelist"),
                    },
                ],
            },
            {
                "title": _("Персонажи"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Персонажи"),
                        "icon": "group",
                        "link": reverse_lazy("admin:character_character_changelist"),
                    },
                    {
                        "title": _("Классы"),
                        "icon": "school",
                        "link": reverse_lazy("admin:character_characterclass_changelist"),
                    },
                    {
                        "title": _("Таланты"),
                        "icon": "emoji_objects",
                        "link": reverse_lazy("admin:character_talent_changelist"),
                    },
                ],
            },
            {
                "title": _("Магия"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Школы магии"),
                        "icon": "auto_fix_high",
                        "link": reverse_lazy("admin:magic_school_changelist"),
                    },
                    {
                        "title": _("Категории заклинаний"),
                        "icon": "category",
                        "link": reverse_lazy("admin:magic_spellcategory_changelist"),
                    },
                    {
                        "title": _("Заклинания"),
                        "icon": "auto_awesome",
                        "link": reverse_lazy("admin:magic_spell_changelist"),
                    },
                ],
            },
            {
                "title": _("Предметы"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Редкости"),
                        "icon": "star",
                        "link": reverse_lazy("admin:items_rarity_changelist"),
                    },
                    {
                        "title": _("Типы предметов"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:items_type_changelist"),
                    },
                    {
                        "title": _("Предметы"),
                        "icon": "shopping_bag",
                        "link": reverse_lazy("admin:items_item_changelist"),
                    },
                ],
            },
            {
                "title": _("Торговля"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Магазины"),
                        "icon": "store",
                        "link": reverse_lazy("admin:shops_shop_changelist"),
                    },
                    {
                        "title": _("Товары в магазинах"),
                        "icon": "sell",
                        "link": reverse_lazy("admin:shops_shopitem_changelist"),
                    },
                ],
            },

            {
                "title": _("Правила и предложения"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Папки правил"),
                        "icon": "folder",
                        "link": reverse_lazy("admin:rulebook_folder_changelist"),
                    },
                    {
                        "title": _("Статьи"),
                        "icon": "description",
                        "link": reverse_lazy("admin:rulebook_article_changelist"),
                    },
                    {
                        "title": _("Предложения по улучшению"),
                        "icon": "tips_and_updates",
                        "link": reverse_lazy("admin:rulebook_improvementproposal_changelist"),
                    },
                ],
            },
            {
                "title": _("Системные инструменты"),
                "collapsible": True,
                "separator": True,
                "items": [
                    {
                        "title": _("Журнал действий"),
                        "icon": "history",
                        "link": reverse_lazy("admin:admin_logentry_changelist"),
                    },
                    # {
                    #     "title": _("Сессии"),
                    #     "icon": "monitor_heart",
                    #     "link": reverse_lazy("admin:sessions_session_changelist"),
                    # },
                ],
            },
        ],
    },
}

ASGI_APPLICATION = 'core.asgi.application'  # замени на своё

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    },
}
