# Generated by Django 5.2.1 on 2026-01-02 17:51

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, verbose_name="URL-имя"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "path",
                    models.CharField(
                        editable=False, max_length=1000, verbose_name="Путь"
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="rulebook.folder",
                        verbose_name="Родитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Папка",
                "verbose_name_plural": "Папки",
                "ordering": ["tree_id", "lft"],
                "unique_together": {("parent", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=250, verbose_name="URL-имя"
                    ),
                ),
                ("content_markdown", models.TextField(verbose_name="Markdown")),
                ("content_html", models.TextField(editable=False, verbose_name="HTML")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "related_articles",
                    models.ManyToManyField(
                        blank=True,
                        symmetrical=False,
                        related_name="related_to",
                        to="rulebook.article",
                        verbose_name="Смежные темы",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="rulebook.folder",
                        verbose_name="Папка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["folder__id", "order"],
                "unique_together": {("folder", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ImprovementProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suggestion", models.TextField(verbose_name="Текст предложения")),
                (
                    "submitter_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Имя автора"
                    ),
                ),
                (
                    "submitter_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email автора"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата подачи"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новое"),
                            ("reviewed", "В работе"),
                            ("accepted", "Принято"),
                            ("rejected", "Отклонено"),
                        ],
                        default="new",
                        help_text="Для внутреннего использования",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обзора"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        help_text="Оставьте пустым для глобальной идеи",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="rulebook.article",
                        verbose_name="Статья",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение по улучшению",
                "verbose_name_plural": "Предложения по улучшению",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
